# Generated by Django 2.0.6 on 2018-07-04 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='generalDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sendingDetails', models.CharField(help_text='Будет отображаться на всех товарах', max_length=320, verbose_name='Детали отправки')),
                ('workEmail', models.EmailField(default='ratviktoriya@gmail.com', max_length=24, verbose_name='Еmail на который будут приходить оповещения о покупателях')),
            ],
            options={
                'verbose_name': 'Детали по товару',
                'verbose_name_plural': 'Общие детали по товару',
            },
        ),
    ]
