# Generated by Django 2.0.7 on 2018-07-08 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0021_auto_20180708_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemimages',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='item.ItemModel'),
        ),
        migrations.AlterField(
            model_name='itemmodel',
            name='description',
            field=models.CharField(max_length=400, verbose_name='Описание товара'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Товар', to='item.ItemModel'),
        ),
    ]
