# Generated by Django 2.0.4 on 2018-06-28 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sliders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('landscapeImage', models.ImageField(upload_to='slider-content/large')),
                ('portraitImage', models.ImageField(upload_to='slider-content/small')),
                ('description', models.CharField(blank=True, default=None, max_length=128)),
                ('isActive', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Слайд',
                'verbose_name_plural': 'Слайды',
            },
        ),
    ]
