# Generated by Django 2.0.6 on 2018-07-04 12:11

from django.db import migrations, models
import helpers
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('landscapeImg', models.ImageField(upload_to='author/landscape', validators=[helpers.isLandscape], verbose_name='Изображение для больших экранов')),
                ('portraitImg', models.ImageField(upload_to='author/portrait', validators=[helpers.isPortrait], verbose_name='Изображение для смартфонов и телефонов')),
                ('authorName', models.CharField(default='Виктория Ратеева', max_length=24, verbose_name='Имя')),
                ('authorJob', models.CharField(max_length=64, verbose_name='Ученая степень, место работы и т.д.')),
                ('authorDescription', models.CharField(default=None, max_length=256, verbose_name='Описание')),
                ('authorPhone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, verbose_name='Телефон рабочий')),
                ('authorPhoneAdd', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, verbose_name='Доп. телефон')),
                ('authorEmail', models.EmailField(default='ratviktoriya@gmail.com', max_length=24, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Информация об авторе',
                'verbose_name_plural': 'Информация об авторе',
            },
        ),
    ]
