# Generated by Django 2.0.6 on 2018-07-04 12:34

from django.db import migrations, models
import django.db.models.deletion
import helpers


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='landscapeImagesSlider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='slider-content/landscape', validators=[helpers.isLandscape], verbose_name='Изображение для больших экранов')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Не портретное изображение',
                'verbose_name_plural': 'Не портретные изображения',
            },
        ),
        migrations.CreateModel(
            name='portraitImagesSlider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='slider-content/portrait', validators=[helpers.isPortrait], verbose_name='Изображение для смартфонов и телефонов')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Портретное изображение',
                'verbose_name_plural': 'Портретные изображения',
            },
        ),
        migrations.CreateModel(
            name='SlidesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=24, verbose_name='Заголовок')),
                ('description', models.CharField(blank=True, default=None, max_length=128, verbose_name='Описание')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('isActive', models.BooleanField(default=True, verbose_name='Показывать слайд')),
                ('landscapeImg', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='landing.landscapeImagesSlider')),
                ('portraitImg', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='landing.portraitImagesSlider')),
            ],
            options={
                'verbose_name': 'Слайд',
                'verbose_name_plural': 'Слайды',
            },
        ),
    ]
