# Generated by Django 2.0.6 on 2018-07-04 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_landscapeimagesslider_portraitimagesslider_slidesmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slidesmodel',
            name='landscapeImg',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='landing.landscapeImagesSlider', verbose_name='Не портретное изображение'),
        ),
        migrations.AlterField(
            model_name='slidesmodel',
            name='portraitImg',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='landing.portraitImagesSlider', verbose_name='Портретное изображение'),
        ),
    ]
