# Generated by Django 2.0.6 on 2018-06-30 11:44

from django.db import migrations, models
import landing.models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_auto_20180628_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slides',
            name='landscapeImage',
            field=models.ImageField(upload_to='slider-content/large', validators=[landing.models.isLandscape], verbose_name='Изображение для больших экранов'),
        ),
        migrations.AlterField(
            model_name='slides',
            name='portraitImage',
            field=models.ImageField(upload_to='slider-content/small', validators=[landing.models.isPortrait], verbose_name='Изображение для смартфонов и телефонов'),
        ),
    ]
