# Generated by Django 2.0.6 on 2018-07-04 13:42

from django.db import migrations, models
import django.db.models.deletion
import helpers


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_auto_20180704_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='authorLandscapeImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='author/landscape', validators=[helpers.isLandscape], verbose_name='Изображение для больших экранов')),
            ],
            options={
                'verbose_name': 'Портретное изображение автора',
                'verbose_name_plural': 'Портретные изображения автора',
            },
        ),
        migrations.CreateModel(
            name='authorPortraitImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='author/portrait', validators=[helpers.isPortrait], verbose_name='Изображение для смартфонов и телефонов')),
            ],
            options={
                'verbose_name': 'Портретное изображение автора',
                'verbose_name_plural': 'Портретные изображения автора',
            },
        ),
        migrations.AlterField(
            model_name='authormodel',
            name='landscapeImg',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='landing.authorLandscapeImages', verbose_name='Не портретное изображение'),
        ),
        migrations.AlterField(
            model_name='authormodel',
            name='portraitImg',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='landing.authorPortraitImages', verbose_name='Портретное изображение'),
        ),
    ]
