# Generated by Django 2.0.6 on 2018-07-01 10:08

from django.db import migrations, models
import landing.models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_auto_20180701_1236'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('landscapeImage', models.ImageField(upload_to='author/large', validators=[landing.models.isLandscape], verbose_name='Изображение для больших экранов')),
                ('portraitImage', models.ImageField(upload_to='author/small', validators=[landing.models.isPortrait], verbose_name='Изображение для смартфонов и телефонов')),
                ('authorName', models.CharField(default='Виктория Ратеева', max_length=24, verbose_name='Имя')),
                ('authorJob', models.CharField(max_length=64, verbose_name='Ученая степень, место работы и т.д.')),
                ('authorDescriptionLarge', models.CharField(max_length=256, verbose_name='Описание полное')),
                ('authorDescriptionShort', models.CharField(max_length=56, verbose_name='Описание короткое для мобильных телефонов')),
                ('authorPhone', models.IntegerField(max_length=24, verbose_name='Телефон рабочий')),
                ('authorPhoneAdd', models.IntegerField(max_length=24, verbose_name='Доп. телефон')),
                ('authorEmail', models.EmailField(blank=True, default='ratviktoriya@gmail.com', max_length=24, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Информация об авторе',
                'verbose_name_plural': 'Информация об авторе',
            },
        ),
        migrations.DeleteModel(
            name='AboutAuthorModel',
        ),
    ]
