# Generated by Django 2.0.6 on 2018-07-01 10:15

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_auto_20180701_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authormodel',
            name='authorPhone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, verbose_name='Телефон рабочий'),
        ),
        migrations.AlterField(
            model_name='authormodel',
            name='authorPhoneAdd',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, verbose_name='Доп. телефон'),
        ),
    ]
