# Generated by Django 2.0.6 on 2018-07-01 10:17

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0006_auto_20180701_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authormodel',
            name='authorPhoneAdd',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, verbose_name='Доп. телефон'),
        ),
    ]
