# Generated by Django 2.0.6 on 2018-07-01 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0007_auto_20180701_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authormodel',
            name='authorEmail',
            field=models.EmailField(default='ratviktoriya@gmail.com', max_length=24, verbose_name='Email'),
        ),
    ]
