# Generated by Django 2.0.6 on 2018-07-04 13:56

from django.db import migrations, models
import helpers


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0007_auto_20180704_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorlandscapeimages',
            name='image',
            field=models.ImageField(upload_to='author/landscape', validators=[helpers.isLandscape], verbose_name='Не портретное изображение'),
        ),
        migrations.AlterField(
            model_name='authorportraitimages',
            name='image',
            field=models.ImageField(upload_to='author/portrait', validators=[helpers.isPortrait], verbose_name='Портретное изображение'),
        ),
    ]
