# Generated by Django 2.0.6 on 2018-07-01 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0008_auto_20180701_1817'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authormodel',
            old_name='authorDescriptionLarge',
            new_name='authorDescription',
        ),
        migrations.RemoveField(
            model_name='authormodel',
            name='authorDescriptionShort',
        ),
    ]
