# Generated by Django 2.0.6 on 2018-07-06 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0008_auto_20180704_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authormodel',
            name='authorDescription',
            field=models.CharField(default=None, max_length=256),
        ),
        migrations.AlterField(
            model_name='slidesmodel',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=128),
        ),
    ]
