# Generated by Django 2.0.6 on 2018-07-06 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0009_auto_20180706_1619'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='portraitImagesSlider',
            new_name='PortraitImageSlider',
        ),
    ]
