# Generated by Django 2.0.6 on 2018-07-01 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0009_auto_20180701_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authormodel',
            name='authorDescription',
            field=models.CharField(max_length=256, verbose_name='Описание'),
        ),
    ]
