# Generated by Django 2.0.6 on 2018-07-06 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0010_auto_20180706_1631'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='landscapeImagesSlider',
            new_name='LandscapeImageSlider',
        ),
    ]
