# Generated by Django 2.0.6 on 2018-07-06 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0011_auto_20180706_1632'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authorlandscapeimages',
            options={'verbose_name': 'Не портретное изображение автора', 'verbose_name_plural': 'Не портретные изображения автора'},
        ),
        migrations.AlterModelOptions(
            name='landscapeimageslider',
            options={'verbose_name': 'Не портретное изображение слайдера', 'verbose_name_plural': 'Не портретные изображения слайдера'},
        ),
        migrations.AlterModelOptions(
            name='portraitimageslider',
            options={'verbose_name': 'Портретное изображение слайдера', 'verbose_name_plural': 'Портретные изображения слайдера'},
        ),
    ]
