# Generated by Django 2.0.6 on 2018-07-06 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0012_auto_20180706_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authormodel',
            name='authorJob',
            field=models.CharField(max_length=64),
        ),
    ]
