# Generated by Django 2.0.7 on 2018-07-08 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0013_auto_20180706_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authormodel',
            name='authorDescription',
            field=models.CharField(default=None, max_length=256, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='authormodel',
            name='authorJob',
            field=models.CharField(max_length=64, verbose_name='Место работы, ученая степень и т.д.'),
        ),
        migrations.AlterField(
            model_name='slidesmodel',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=128, verbose_name='Основной текст'),
        ),
    ]
