# Generated by Django 2.0.7 on 2018-07-08 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0014_auto_20180708_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authormodel',
            name='landscapeImg',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='landing.authorLandscapeImages', verbose_name='Не портретное изображение'),
        ),
        migrations.AlterField(
            model_name='authormodel',
            name='portraitImg',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='landing.authorPortraitImages', verbose_name='Портретное изображение'),
        ),
        migrations.AlterField(
            model_name='slidesmodel',
            name='landscapeImg',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='landing.LandscapeImageSlider', verbose_name='Не портретное изображение'),
        ),
        migrations.AlterField(
            model_name='slidesmodel',
            name='portraitImg',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='landing.PortraitImageSlider', verbose_name='Портретное изображение'),
        ),
    ]
